{"name": "test_get_auth_with_errusername", "status": "passed", "description": "测试输入错误uersname获取access_token", "attachments": [{"name": "LoginForAccessTokenApiLoginTokenPostAPI", "source": "9e8da513-05f2-484c-9356-9fdc51d5fb62-attachment.json", "type": "application/json"}, {"name": "log", "source": "d469ba9f-a4d8-4160-a90d-8e90ecff381b-attachment.txt", "type": "text/plain"}], "start": 1758157789562, "stop": 1758157789574, "uuid": "076f88ff-919d-4a3d-a671-6d82f2c636e9", "historyId": "89f63c5a3aa1eed51ca03ce81f01396e", "testCaseId": "88078b7220eac28562d016da3f959de8", "fullName": "testcases.test_scenario.auth.test_auth#test_get_auth_with_errusername", "labels": [{"name": "tag", "value": "auth"}, {"name": "parentSuite", "value": "testcases.test_scenario.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "admin"}, {"name": "thread", "value": "34480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_scenario.auth.test_auth"}]}