{"name": "test_get_auth_with_errusername", "status": "passed", "description": "测试输入错误uersname获取access_token", "attachments": [{"name": "LoginForAccessTokenApiLoginTokenPostAPI", "source": "92f732d4-70d8-45ea-9bfa-a850b4d0c82b-attachment.json", "type": "application/json"}, {"name": "log", "source": "a5a1d1b9-40f4-4159-9d90-8677cf60607d-attachment.txt", "type": "text/plain"}], "start": 1758184950063, "stop": 1758184950077, "uuid": "35d89ac7-7caf-4c0b-8b41-58c61947f096", "historyId": "89f63c5a3aa1eed51ca03ce81f01396e", "testCaseId": "88078b7220eac28562d016da3f959de8", "fullName": "testcases.test_scenario.auth.test_auth#test_get_auth_with_errusername", "labels": [{"name": "tag", "value": "auth"}, {"name": "parentSuite", "value": "testcases.test_scenario.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "admin"}, {"name": "thread", "value": "22120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_scenario.auth.test_auth"}]}